@startuml Update Appointment

header Sample VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Update Appointment"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:appointments/" as routerAppointments
participant "<<controllers>>\n:updateFinish" as controllersUpdateAppointment
participant "<<model>>\n:Appointment" as modelAppointment
database "<<MongoDB>>\n:appointments" as AppointmentsDatabase

client->server ++:req.put('/api/v1/appointments/:id')
server->routerAppointments ++:app.put('/api/v1/appointments/:id', updateFinish)
routerAppointments -> controllersUpdateAppointment ++:UpdateFinish(req, res, next)
activate controllersUpdateAppointment

controllersUpdateAppointment->modelAppointment ++:Appointment.findById(req.params.id,finish:false)
activate modelAppointment
modelAppointment --> controllersUpdateAppointment --:appointment

alt "User unauthorized to update"
    controllersUpdateAppointment->client --:res.status(401).json({ success: false, message: "User is not authorized to update this" })
else "User authorized to update"
    modelAppointment -> AppointmentsDatabase: AppointmentSchema
    AppointmentsDatabase --> modelAppointment --:appointment
    modelAppointment --> controllersUpdateAppointment --:updatedFinishAppointment
    controllersUpdateAppointment->client --:res.status(200).json({ success: true, data: updatedAppointment })
end

deactivate modelAppointment
deactivate controllersUpdateAppointment
@enduml
