@startuml

top to bottom direction

skinparam actorStyle awesome
skinparam usecase {
    BackgroundColor White
    BorderColor Black
}

actor User
rectangle "Dentist_Booking System" {
    rectangle "Dentist" {
        usecase "View Dentist(s)" as VD
        usecase "Manage All Dentists" as MAD
    }
    ' rectangle "Middleware" {
    '     usecase "Protect" as Protect
    '     usecase "Authorize" as Authorize
    ' }
    rectangle "Appointment" {
        usecase "View Appointment(s)" as VA
        usecase "Manage Appointment" as MA
        usecase "getLatestAppointments" as GLA
        usecase "updateFinish" as UF
    }
    rectangle "Account" {
        usecase "GetProfile" as GP
        usecase "ManageProfile" as MP
    }
}

User -- VD

User -- MA
User -- VA
User -- GLA
User -- GP
User -- MP

actor Admin
VD -- Admin
MAD -- Admin
VA -- Admin
MA -- Admin
GLA -- Admin
UF -- Admin
GP -- Admin
MP -- Admin

@enduml
